import json
import math
import re
from pathlib import Path


TOKEN_RE = re.compile(r"[a-zA-Z0-9']+")


def tokenize(text):
    return TOKEN_RE.findall((text or "").lower())


def feature_tokens(text):
    words = tokenize(text)
    features = list(words)
    features.extend(
        "__bg__" + words[i] + "_" + words[i + 1]
        for i in range(len(words) - 1)
    )
    return features


def softmax(values):
    if not values:
        return []

    maximum = max(values)
    exps = [
        math.exp(max(-60.0, min(60.0, value - maximum)))
        for value in values
    ]
    total = sum(exps) or 1.0
    return [value / total for value in exps]


class Module:
    """
    Apollo neural-network visualizer.

    It reads the model generated by the neural_learning module from:

        <Apollo>/storage/state/neural_learning_state.json

    It never edits the neural model.
    """

    def __init__(self, context=None):
        context = context or {}
        self.base_dir = Path(context.get("base_dir", ".")).resolve()
        self.validation = bool(context.get("validation", False))
        self.state_path = self.base_dir / "storage" / "state" / "neural_learning_state.json"
        self._latest_text = "Apollo online"
        self._latest_visual = None
        self._latest_error = ""
        self._latest_revision = 0

    def tools(self):
        return [
            {
                "name": "visual_neural_status",
                "description": (
                    "Return a summary of the neural_learning model available for "
                    "visualization."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {}
                }
            },
            {
                "name": "visualize_input",
                "description": (
                    "Run text through Apollo's trained neural network and return "
                    "input features, hidden activations, output probabilities and "
                    "strongest learned connections for visualization."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "text": {"type": "string"},
                        "max_input_nodes": {"type": "integer"},
                        "max_hidden_nodes": {"type": "integer"}
                    },
                    "required": ["text"]
                }
            }
        ]

    def _load_state(self):
        if not self.state_path.exists():
            return {
                "exists": False,
                "trained": False,
                "ready_for_use": False,
                "examples": [],
                "vocab": [],
                "labels": [],
                "w1": [],
                "b1": [],
                "w2": [],
                "b2": [],
                "hidden_size": 0,
                "last_training": {},
            }

        try:
            data = json.loads(
                self.state_path.read_text(
                    encoding="utf-8",
                    errors="replace",
                )
            )
        except Exception as exc:
            raise RuntimeError(
                f"Could not read neural model state: {exc}"
            )

        data["exists"] = True
        return data

    @staticmethod
    def _vector(text, vocab):
        counts = {}
        for feature in feature_tokens(text):
            counts[feature] = counts.get(feature, 0) + 1

        maximum = max(counts.values(), default=1)

        return [
            counts.get(word, 0) / maximum
            for word in vocab
        ]

    @staticmethod
    def _dot(weights, values, bias):
        return bias + sum(
            weight * value
            for weight, value in zip(weights, values)
        )

    def _forward(self, text, state):
        vocab = list(state.get("vocab", []))
        labels = list(state.get("labels", []))
        w1 = list(state.get("w1", []))
        b1 = list(state.get("b1", []))
        w2 = list(state.get("w2", []))
        b2 = list(state.get("b2", []))

        if not state.get("trained"):
            raise RuntimeError(
                "Apollo's neural_learning module has not been trained yet."
            )

        if not vocab or not labels or not w1 or not w2:
            raise RuntimeError(
                "Apollo's neural model state is incomplete."
            )

        x = self._vector(text, vocab)

        hidden = [
            math.tanh(
                self._dot(
                    w1[index],
                    x,
                    b1[index] if index < len(b1) else 0.0,
                )
            )
            for index in range(len(w1))
        ]

        logits = [
            self._dot(
                w2[index],
                hidden,
                b2[index] if index < len(b2) else 0.0,
            )
            for index in range(len(w2))
        ]

        probs = softmax(logits)

        return x, hidden, probs

    def _status(self):
        state = self._load_state()

        return {
            "model_found": bool(state.get("exists")),
            "trained": bool(state.get("trained")),
            "ready_for_use": bool(state.get("ready_for_use")),
            "example_count": len(state.get("examples", [])),
            "vocab_size": len(state.get("vocab", [])),
            "hidden_size": len(state.get("w1", [])),
            "labels": list(state.get("labels", [])),
            "last_training": dict(state.get("last_training", {})),
            "state_file": str(self.state_path),
        }

    def _visualize(
        self,
        text,
        max_input_nodes=12,
        max_hidden_nodes=16,
    ):
        text = str(text or "").strip()
        if not text:
            raise ValueError("text cannot be empty.")

        try:
            max_input_nodes = int(max_input_nodes)
        except (TypeError, ValueError):
            max_input_nodes = 12

        try:
            max_hidden_nodes = int(max_hidden_nodes)
        except (TypeError, ValueError):
            max_hidden_nodes = 16

        max_input_nodes = max(4, min(max_input_nodes, 30))
        max_hidden_nodes = max(4, min(max_hidden_nodes, 32))

        state = self._load_state()
        x, hidden, probs = self._forward(text, state)

        vocab = list(state.get("vocab", []))
        labels = list(state.get("labels", []))
        w1 = list(state.get("w1", []))
        w2 = list(state.get("w2", []))

        # Active input features, strongest first.
        active_inputs = [
            (index, vocab[index], value)
            for index, value in enumerate(x)
            if value > 0
        ]
        active_inputs.sort(
            key=lambda item: item[2],
            reverse=True,
        )
        active_inputs = active_inputs[:max_input_nodes]

        # Hidden nodes with the highest absolute activation.
        hidden_nodes = [
            (index, value)
            for index, value in enumerate(hidden)
        ]
        hidden_nodes.sort(
            key=lambda item: abs(item[1]),
            reverse=True,
        )
        hidden_nodes = hidden_nodes[:max_hidden_nodes]

        hidden_index_set = {
            index for index, _ in hidden_nodes
        }
        input_index_set = {
            index for index, _, _ in active_inputs
        }

        # Strongest visible input -> hidden edges.
        input_hidden_edges = []

        for hidden_index in hidden_index_set:
            row = (
                w1[hidden_index]
                if hidden_index < len(w1)
                else []
            )

            for input_index in input_index_set:
                if input_index >= len(row):
                    continue

                weight = float(row[input_index])

                if abs(weight) < 0.01:
                    continue

                contribution = weight * x[input_index]

                input_hidden_edges.append({
                    "input_index": input_index,
                    "hidden_index": hidden_index,
                    "weight": round(weight, 5),
                    "contribution": round(contribution, 5),
                })

        input_hidden_edges.sort(
            key=lambda edge: abs(edge["contribution"]),
            reverse=True,
        )
        input_hidden_edges = input_hidden_edges[:60]

        # Strongest visible hidden -> output edges.
        hidden_output_edges = []

        for output_index, label in enumerate(labels):
            row = (
                w2[output_index]
                if output_index < len(w2)
                else []
            )

            for hidden_index in hidden_index_set:
                if hidden_index >= len(row):
                    continue

                weight = float(row[hidden_index])
                contribution = weight * hidden[hidden_index]

                hidden_output_edges.append({
                    "hidden_index": hidden_index,
                    "output_index": output_index,
                    "label": label,
                    "weight": round(weight, 5),
                    "contribution": round(contribution, 5),
                })

        hidden_output_edges.sort(
            key=lambda edge: abs(edge["contribution"]),
            reverse=True,
        )
        hidden_output_edges = hidden_output_edges[:80]

        outputs = [
            {
                "index": index,
                "label": labels[index],
                "probability": round(
                    probs[index],
                    6,
                ),
            }
            for index in range(
                min(len(labels), len(probs))
            )
        ]
        outputs.sort(
            key=lambda item: item["probability"],
            reverse=True,
        )

        return {
            "text": text,
            "ready_for_use": bool(
                state.get("ready_for_use")
            ),
            "input_nodes": [
                {
                    "index": index,
                    "feature": feature,
                    "activation": round(value, 5),
                }
                for index, feature, value in active_inputs
            ],
            "hidden_nodes": [
                {
                    "index": index,
                    "activation": round(value, 6),
                }
                for index, value in hidden_nodes
            ],
            "outputs": outputs,
            "input_hidden_edges": input_hidden_edges,
            "hidden_output_edges": hidden_output_edges,
            "model": {
                "vocab_size": len(vocab),
                "hidden_size": len(hidden),
                "output_size": len(labels),
                "labels": labels,
            },
        }

    def observe_text(self, text):
        text = str(text or "").strip()
        if not text:
            return {"observed": False, "reason": "empty_text"}

        self._latest_text = text
        self._latest_revision += 1

        try:
            self._latest_visual = self._visualize(
                text,
                max_input_nodes=8,
                max_hidden_nodes=12,
            )
            self._latest_error = ""
            outputs = self._latest_visual.get("outputs", [])
            return {
                "observed": True,
                "text": text,
                "top_output": outputs[0] if outputs else None,
            }
        except Exception as exc:
            self._latest_visual = None
            self._latest_error = str(exc)
            return {
                "observed": True,
                "text": text,
                "error": self._latest_error,
            }

    def self_test(self):
        # Validator-safe API test. A real trained state file is not required.
        names = {
            item["name"]
            for item in self.tools()
        }

        assert "visual_neural_status" in names
        assert "visualize_input" in names

        status = self._status()
        assert "trained" in status
        assert "state_file" in status

        return "Neural Visualizer API/state tests passed."


    def build_hub_widget(
        self,
        parent=None,
        ui_context=None,
    ):
        from PySide6.QtCore import QPointF, Qt, QTimer
        from PySide6.QtGui import QColor, QFont, QPainter, QPen
        from PySide6.QtWidgets import QFrame, QVBoxLayout, QLabel, QWidget

        module = self

        class LiveCanvas(QWidget):
            def __init__(self):
                super().__init__()
                self.data = None
                self.message = ""
                self.setMinimumHeight(260)

            def paintEvent(self, event):
                painter = QPainter(self)
                painter.setRenderHint(QPainter.RenderHint.Antialiasing)
                rect = self.rect()
                painter.fillRect(rect, QColor("#081d1e"))

                if not self.data:
                    painter.setPen(QColor("#7eaaa3"))
                    painter.setFont(QFont("Segoe UI", 10))
                    painter.drawText(
                        rect,
                        Qt.AlignCenter,
                        self.message or (
                            "Neural Visualizer is active.\\n"
                            "Train Neural Learning to display live activity."
                        ),
                    )
                    return

                inputs = self.data.get("input_nodes", [])
                hidden = self.data.get("hidden_nodes", [])
                outputs = self.data.get("outputs", [])[:4]

                left_x = 55
                centre_x = rect.width() * 0.50
                right_x = rect.width() - 90

                def positions(count, x):
                    if count <= 0:
                        return []
                    top = 32
                    bottom = rect.height() - 32
                    if count == 1:
                        return [QPointF(x, (top + bottom) / 2)]
                    return [
                        QPointF(
                            x,
                            top + (bottom - top) * index / (count - 1),
                        )
                        for index in range(count)
                    ]

                input_points = positions(len(inputs), left_x)
                hidden_points = positions(len(hidden), centre_x)
                output_points = positions(len(outputs), right_x)

                input_lookup = {
                    item["index"]: point
                    for item, point in zip(inputs, input_points)
                }
                hidden_lookup = {
                    item["index"]: point
                    for item, point in zip(hidden, hidden_points)
                }
                output_lookup = {
                    item["index"]: point
                    for item, point in zip(outputs, output_points)
                }

                for edge in self.data.get("input_hidden_edges", [])[:32]:
                    start = input_lookup.get(edge["input_index"])
                    end = hidden_lookup.get(edge["hidden_index"])
                    if start is None or end is None:
                        continue
                    value = float(edge.get("contribution", 0))
                    color = (
                        QColor(70, 200, 160, 110)
                        if value >= 0
                        else QColor(220, 90, 105, 110)
                    )
                    painter.setPen(QPen(color, 1.0 + min(2.0, abs(value) * 2.0)))
                    painter.drawLine(start, end)

                for edge in self.data.get("hidden_output_edges", [])[:36]:
                    start = hidden_lookup.get(edge["hidden_index"])
                    end = output_lookup.get(edge["output_index"])
                    if start is None or end is None:
                        continue
                    value = float(edge.get("contribution", 0))
                    color = (
                        QColor(90, 190, 235, 120)
                        if value >= 0
                        else QColor(225, 105, 120, 120)
                    )
                    painter.setPen(QPen(color, 1.0 + min(2.0, abs(value) * 2.0)))
                    painter.drawLine(start, end)

                painter.setFont(QFont("Segoe UI", 8))

                for _, point in zip(inputs, input_points):
                    painter.setBrush(QColor("#55c9ad"))
                    painter.setPen(QPen(QColor("#b8f4e6"), 1))
                    painter.drawEllipse(point, 5, 5)

                for item, point in zip(hidden, hidden_points):
                    activation = abs(float(item.get("activation", 0)))
                    radius = 5 + min(6, activation * 6)
                    painter.setBrush(
                        QColor(
                            60,
                            int(100 + min(150, activation * 150)),
                            190,
                        )
                    )
                    painter.setPen(QPen(QColor("#c9f7ee"), 1))
                    painter.drawEllipse(point, radius, radius)

                for item, point in zip(outputs, output_points):
                    probability = float(item.get("probability", 0))
                    painter.setBrush(
                        QColor(
                            60,
                            int(110 + probability * 130),
                            175,
                        )
                    )
                    painter.setPen(QPen(QColor("#d9fff7"), 1))
                    radius = 7 + probability * 5
                    painter.drawEllipse(point, radius, radius)
                    painter.setPen(QColor("#d9eee9"))
                    painter.drawText(
                        int(point.x() + 15),
                        int(point.y() + 4),
                        f"{item.get('label')} {probability * 100:.0f}%",
                    )

        frame = QFrame(parent)
        frame.setObjectName("card")
        layout = QVBoxLayout(frame)

        title = QLabel("Live Neural Activity")
        title.setStyleSheet(
            "font-size:14px;font-weight:700;color:#e9fffb;"
        )
        layout.addWidget(title)

        status = QLabel("Neural Visualizer active")
        status.setStyleSheet("color:#75d8c5;")
        layout.addWidget(status)

        canvas = LiveCanvas()
        layout.addWidget(canvas, 1)

        last_seen = {"revision": -1}

        def refresh():
            if module._latest_revision == last_seen["revision"]:
                return

            last_seen["revision"] = module._latest_revision

            if module._latest_visual is not None:
                canvas.data = module._latest_visual
                canvas.message = ""
                outputs = module._latest_visual.get("outputs", [])

                if outputs:
                    top = outputs[0]
                    status.setText(
                        "Active • "
                        f"{top.get('label')} "
                        f"{float(top.get('probability', 0)) * 100:.1f}% "
                        f"• {module._latest_text[:80]}"
                    )
                else:
                    status.setText("Active • no output labels")
            else:
                canvas.data = None

                if module._latest_error:
                    canvas.message = (
                        "Neural Visualizer is active.\\n"
                        + module._latest_error
                    )
                    status.setText(
                        "Active • waiting for a trained neural model"
                    )
                else:
                    canvas.message = (
                        "Neural Visualizer is active.\\n"
                        "Waiting for chat activity."
                    )
                    status.setText("Active • waiting for chat activity")

            canvas.update()

        if self._latest_revision == 0:
            self.observe_text(self._latest_text)

        timer = QTimer(frame)
        timer.setInterval(350)
        timer.timeout.connect(refresh)
        timer.start()
        refresh()

        return frame

    def build_ui(
        self,
        parent=None,
        ui_context=None,
    ):
        # Qt imports are intentionally lazy so headless Apollo validation works.
        from PySide6.QtCore import (
            QPointF,
            QRectF,
            Qt,
            QTimer,
        )
        from PySide6.QtGui import (
            QColor,
            QFont,
            QPainter,
            QPen,
        )
        from PySide6.QtWidgets import (
            QWidget,
            QVBoxLayout,
            QHBoxLayout,
            QLabel,
            QLineEdit,
            QPushButton,
            QTextBrowser,
            QMessageBox,
            QSizePolicy,
        )

        module = self

        class NetworkCanvas(QWidget):
            def __init__(self):
                super().__init__()
                self.data = None
                self.setMinimumHeight(430)
                self.setSizePolicy(
                    QSizePolicy.Policy.Expanding,
                    QSizePolicy.Policy.Expanding,
                )

            def set_data(self, data):
                self.data = data
                self.update()

            @staticmethod
            def _activation_color(value):
                value = max(-1.0, min(1.0, float(value)))

                if value >= 0:
                    intensity = int(
                        90 + 165 * value
                    )
                    return QColor(
                        60,
                        intensity,
                        190,
                    )

                intensity = int(
                    90 + 165 * abs(value)
                )
                return QColor(
                    intensity,
                    90,
                    105,
                )

            def paintEvent(self, event):
                painter = QPainter(self)
                painter.setRenderHint(
                    QPainter.RenderHint.Antialiasing
                )

                rect = self.rect()
                painter.fillRect(
                    rect,
                    QColor("#0b1715"),
                )

                if not self.data:
                    painter.setPen(
                        QColor("#8cb8b0")
                    )
                    painter.setFont(
                        QFont("Segoe UI", 12)
                    )
                    painter.drawText(
                        rect,
                        Qt.AlignmentFlag.AlignCenter,
                        (
                            "Train Apollo's Neural Learning module,\n"
                            "then enter text and press Visualize."
                        ),
                    )
                    return

                inputs = self.data.get(
                    "input_nodes",
                    [],
                )
                hidden = self.data.get(
                    "hidden_nodes",
                    [],
                )
                outputs = self.data.get(
                    "outputs",
                    [],
                )

                margin = 55
                left_x = margin + 50
                hidden_x = rect.width() / 2
                right_x = rect.width() - margin - 80

                def positions(
                    count,
                    x,
                    top=55,
                    bottom_margin=50,
                ):
                    if count <= 0:
                        return {}

                    usable = max(
                        80,
                        rect.height()
                        - top
                        - bottom_margin,
                    )

                    if count == 1:
                        return {
                            0: QPointF(
                                x,
                                top + usable / 2,
                            )
                        }

                    return {
                        index: QPointF(
                            x,
                            top
                            + usable
                            * index
                            / (count - 1),
                        )
                        for index in range(count)
                    }

                input_pos = positions(
                    len(inputs),
                    left_x,
                )
                hidden_pos = positions(
                    len(hidden),
                    hidden_x,
                )
                output_pos = positions(
                    len(outputs),
                    right_x,
                )

                input_lookup = {
                    item["index"]: position
                    for item, position in zip(
                        inputs,
                        input_pos.values(),
                    )
                }
                hidden_lookup = {
                    item["index"]: position
                    for item, position in zip(
                        hidden,
                        hidden_pos.values(),
                    )
                }
                output_lookup = {
                    item["index"]: position
                    for item, position in zip(
                        outputs,
                        output_pos.values(),
                    )
                }

                # Input -> hidden connections.
                for edge in self.data.get(
                    "input_hidden_edges",
                    [],
                ):
                    start = input_lookup.get(
                        edge["input_index"]
                    )
                    end = hidden_lookup.get(
                        edge["hidden_index"]
                    )

                    if start is None or end is None:
                        continue

                    contribution = float(
                        edge.get(
                            "contribution",
                            0,
                        )
                    )
                    strength = min(
                        1.0,
                        abs(contribution),
                    )

                    color = (
                        QColor(70, 200, 160)
                        if contribution >= 0
                        else QColor(220, 90, 105)
                    )
                    color.setAlpha(
                        int(
                            40
                            + 160
                            * strength
                        )
                    )

                    pen = QPen(
                        color,
                        1.0 + 2.4 * strength,
                    )
                    painter.setPen(pen)
                    painter.drawLine(
                        start,
                        end,
                    )

                # Hidden -> output connections.
                for edge in self.data.get(
                    "hidden_output_edges",
                    [],
                ):
                    start = hidden_lookup.get(
                        edge["hidden_index"]
                    )
                    end = output_lookup.get(
                        edge["output_index"]
                    )

                    if start is None or end is None:
                        continue

                    contribution = float(
                        edge.get(
                            "contribution",
                            0,
                        )
                    )
                    strength = min(
                        1.0,
                        abs(contribution),
                    )

                    color = (
                        QColor(100, 190, 235)
                        if contribution >= 0
                        else QColor(225, 105, 120)
                    )
                    color.setAlpha(
                        int(
                            45
                            + 170
                            * strength
                        )
                    )

                    painter.setPen(
                        QPen(
                            color,
                            1.0
                            + 2.6
                            * strength,
                        )
                    )
                    painter.drawLine(
                        start,
                        end,
                    )

                # Column headings.
                painter.setFont(
                    QFont(
                        "Segoe UI",
                        10,
                        QFont.Weight.Bold,
                    )
                )
                painter.setPen(
                    QColor("#9bcac1")
                )
                painter.drawText(
                    int(left_x - 45),
                    27,
                    "INPUT FEATURES",
                )
                painter.drawText(
                    int(hidden_x - 42),
                    27,
                    "HIDDEN",
                )
                painter.drawText(
                    int(right_x - 25),
                    27,
                    "OUTPUT",
                )

                # Input nodes.
                painter.setFont(
                    QFont("Segoe UI", 8)
                )
                for item, point in zip(
                    inputs,
                    input_pos.values(),
                ):
                    radius = 8
                    painter.setBrush(
                        QColor("#56c7ac")
                    )
                    painter.setPen(
                        QPen(
                            QColor("#b7f4e5"),
                            1,
                        )
                    )
                    painter.drawEllipse(
                        point,
                        radius,
                        radius,
                    )

                    feature = str(
                        item.get(
                            "feature",
                            "",
                        )
                    )
                    if feature.startswith(
                        "__bg__"
                    ):
                        feature = feature[6:].replace(
                            "_",
                            " ",
                        )

                    painter.setPen(
                        QColor("#b7d7d1")
                    )
                    painter.drawText(
                        QRectF(
                            point.x() - 135,
                            point.y() - 9,
                            120,
                            22,
                        ),
                        Qt.AlignmentFlag.AlignRight
                        | Qt.AlignmentFlag.AlignVCenter,
                        feature[:22],
                    )

                # Hidden nodes.
                for item, point in zip(
                    hidden,
                    hidden_pos.values(),
                ):
                    activation = float(
                        item.get(
                            "activation",
                            0,
                        )
                    )
                    radius = (
                        8
                        + 7
                        * min(
                            1.0,
                            abs(activation),
                        )
                    )

                    painter.setBrush(
                        self._activation_color(
                            activation
                        )
                    )
                    painter.setPen(
                        QPen(
                            QColor("#d8f7f0"),
                            1,
                        )
                    )
                    painter.drawEllipse(
                        point,
                        radius,
                        radius,
                    )

                    painter.setPen(
                        QColor("#b7d7d1")
                    )
                    painter.drawText(
                        QRectF(
                            point.x() - 25,
                            point.y() - 8,
                            50,
                            16,
                        ),
                        Qt.AlignmentFlag.AlignCenter,
                        str(
                            item.get(
                                "index",
                                "",
                            )
                        ),
                    )

                # Output nodes.
                painter.setFont(
                    QFont("Segoe UI", 9)
                )
                for item, point in zip(
                    outputs,
                    output_pos.values(),
                ):
                    probability = float(
                        item.get(
                            "probability",
                            0,
                        )
                    )

                    radius = (
                        10
                        + 10
                        * probability
                    )

                    painter.setBrush(
                        QColor(
                            65,
                            int(
                                100
                                + 145
                                * probability
                            ),
                            180,
                        )
                    )
                    painter.setPen(
                        QPen(
                            QColor("#d7f9f2"),
                            1.2,
                        )
                    )
                    painter.drawEllipse(
                        point,
                        radius,
                        radius,
                    )

                    label = str(
                        item.get(
                            "label",
                            "",
                        )
                    )
                    confidence = (
                        probability * 100
                    )

                    painter.setPen(
                        QColor("#d7eee9")
                    )
                    painter.drawText(
                        QRectF(
                            point.x() + 20,
                            point.y() - 12,
                            170,
                            28,
                        ),
                        Qt.AlignmentFlag.AlignLeft
                        | Qt.AlignmentFlag.AlignVCenter,
                        (
                            f"{label} "
                            f"{confidence:.1f}%"
                        ),
                    )

        page = QWidget(parent)
        layout = QVBoxLayout(page)

        title = QLabel(
            "Neural Visualizer"
        )
        title.setStyleSheet(
            "font-size:22px;"
            "font-weight:700;"
            "color:#e7fffb;"
        )

        info = QLabel(
            "Watch text flow through Apollo's trained neural classifier. "
            "Lines show learned connections; node brightness/size shows activation."
        )
        info.setWordWrap(True)
        info.setStyleSheet(
            "color:#91bdb6;"
        )

        controls = QHBoxLayout()

        text_input = QLineEdit()
        text_input.setPlaceholderText(
            "Try: write me a python program"
        )

        visualize_button = QPushButton(
            "Visualize"
        )
        refresh_button = QPushButton(
            "Refresh Model"
        )

        controls.addWidget(
            text_input,
            1,
        )
        controls.addWidget(
            visualize_button
        )
        controls.addWidget(
            refresh_button
        )

        status_label = QLabel(
            "Model: checking..."
        )
        status_label.setStyleSheet(
            "color:#78d9c5;"
        )

        canvas = NetworkCanvas()

        details = QTextBrowser()
        details.setMaximumHeight(150)
        details.setPlaceholderText(
            "Prediction and model details appear here."
        )

        layout.addWidget(title)
        layout.addWidget(info)
        layout.addLayout(controls)
        layout.addWidget(status_label)
        layout.addWidget(canvas, 1)
        layout.addWidget(details)

        def refresh_status():
            try:
                status = module._status()

                if not status["model_found"]:
                    status_label.setText(
                        "Model: no neural_learning_state.json found"
                    )
                elif not status["trained"]:
                    status_label.setText(
                        "Model: found, but not trained yet"
                    )
                else:
                    status_label.setText(
                        "Model: trained | "
                        f"{status.get('example_count')} examples | "
                        f"{status.get('vocab_size')} features | "
                        f"{status.get('hidden_size')} hidden nodes | "
                        f"Ready for Apollo chat: {status.get('ready_for_use')}"
                    )

            except Exception as exc:
                status_label.setText(
                    f"Model error: {exc}"
                )

        def visualize():
            try:
                result = module._visualize(
                    text_input.text(),
                    max_input_nodes=12,
                    max_hidden_nodes=16,
                )

                canvas.set_data(result)

                outputs = result.get(
                    "outputs",
                    []
                )

                output_lines = [
                    (
                        f"{item['label']}: "
                        f"{item['probability'] * 100:.2f}%"
                    )
                    for item in outputs
                ]

                features = [
                    item["feature"]
                    for item in result.get(
                        "input_nodes",
                        [],
                    )
                ]

                details.setPlainText(
                    f"Input: {result.get('text')}\n"
                    f"Active visible features: {', '.join(features) or 'none'}\n"
                    f"Ready for Apollo chat: {result.get('ready_for_use')}\n\n"
                    + "\n".join(output_lines)
                )

                refresh_status()

            except Exception as exc:
                QMessageBox.warning(
                    page,
                    "Neural Visualizer",
                    str(exc),
                )

        visualize_button.clicked.connect(
            visualize
        )
        text_input.returnPressed.connect(
            visualize
        )
        refresh_button.clicked.connect(
            refresh_status
        )

        timer = QTimer(page)
        timer.setInterval(2000)
        timer.timeout.connect(
            refresh_status
        )
        timer.start()

        refresh_status()

        return page

    def run(self, action, arguments):
        arguments = arguments or {}

        if action == "visual_neural_status":
            return self._status()

        if action == "visualize_input":
            return self._visualize(
                arguments.get("text"),
                arguments.get(
                    "max_input_nodes",
                    12,
                ),
                arguments.get(
                    "max_hidden_nodes",
                    16,
                ),
            )

        if action == "observe_text":
            return self.observe_text(
                arguments.get("text")
            )

        raise KeyError(
            f"Unknown action: {action}"
        )
